---
- name: Playbook to Install tomcat
  hosts: dev
  tasks:
  - name: Install tomcat
    package:
      name: tomcat
      state: present

  - name: Start tomcat Service
    service:
      name: tomcat
      state: started
