# Autor: Francisco Javiuer Gutierrez | Unix/Linux Architect & Cloud Engineer
---
- name: Install and Configure HAProxy
  hosts: masters
  become: true
  tasks:
    - name: Instalar HAProxy
      yum:
        name: haproxy
        state: present

    - name: Configurar HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy

    - name: Iniciar y habilitar HAProxy
      systemd:
        name: haproxy
        state: started
        enabled: yes

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted
        enabled: yes

