control_plane_endpoint: "192.168.20.35:8443"
pod_network_cidr: "10.244.0.0/16"
bootstrap_token: "{{ lookup('password', '/dev/null length=6 chars=digits') }}.{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"
ca_cert_hash: "{{ lookup('password', '/dev/null length=64 chars=hexdigits') }}"

