---
- name: Crear namespace para ArgoCD
  command: kubectl create namespace argocd
  ignore_errors: yes

- name: Desplegar ArgoCD
  command: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

- name: Esperando a que ArgoCD esté listo
  shell: |
    kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server -o jsonpath='{.items[0].status.phase}'
  register: pod_status
  until: pod_status.stdout == "Running"
  retries: 20
  delay: 15

- name: Obtener clave de administrador inicial de ArgoCD
  shell: |
    kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath="{.data.password}" | base64 --decode
  register: admin_password

- name: Mostrar clave de administrador inicial de ArgoCD
  debug:
    msg: "Clave de administrador inicial de ArgoCD: {{ admin_password.stdout }}"