---
- name: Instalar Docker y crear contenedor Apache con p치gina personalizada en CentOS
  hosts: servidor
  become: true
  tasks:
    - name: Instalar paquetes necesarios
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Agregar el repositorio Docker
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Instalar Docker
      yum:
        name: docker-ce
        state: present

    - name: Iniciar y habilitar Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Crear directorio para archivos Docker
      file:
        path: /opt/docker-apache
        state: directory

    - name: Crear Dockerfile
      copy:
        dest: /opt/docker-apache/Dockerfile
        content: |
          FROM httpd:latest
          COPY index.html /usr/local/apache2/htdocs/

    - name: Crear p치gina personalizada
      copy:
        dest: /opt/docker-apache/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>P치gina de Prueba de Apache</title>
          </head>
          <body>
              <h1>Miguel, Apache funciona</h1>
              <p>Esta es una p치gina de prueba personalizada para Miguel</p>
          </body>
          </html>

    - name: Construir imagen Docker personalizada
      command: docker build -t custom_apache /opt/docker-apache

    - name: Ejecutar contenedor Apache personalizado
      command: docker run -d --name apache_server -p 80:80 custom_apache

