- name: Install Calico
  become: yes
  shell: kubectl apply -f https://docs.projectcalico.org/v3.21/manifests/calico.yaml

- name: Wait for Calico to be ready
  become: yes
  shell: kubectl get pod -n kube-system -l k8s-app=calico-kube-controllers --field-selector=status.phase=Running --no-headers | wc -l | grep 2

- name: Set IP Forwarding for Calico
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes