- name: Generate and store join command for master
  set_fact:
    join_command: "kubeadm token create --print-join-command"

- name: Join Kubernetes master nodes
  shell: "{{ join_command.stdout }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: kubeadm_role == 'master'
