- name: Initialize Kubernetes master nodes
  include_tasks: initialize-master.yml
  when: kubeadm_role == 'master'

- name: Join Kubernetes master nodes
  include_tasks: join-masters.yml
  when: kubeadm_role == 'master'

- name: Join Kubernetes worker nodes
  include_tasks: join-workers.yml
  when: kubeadm_role == 'worker'

- name: Set IP Forwarding for Calico
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes