---
- name: Configure Kubernetes firewall rules and enable IP forwarding
  hosts: all
  become: yes

  tasks:
    - name: Install firewalld
      package:
        name: firewalld
        state: present

    - name: Start firewalld and enable it on boot
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Define Kubernetes ports
      set_fact:
        kubernetes_ports:
          - { port: 6443, protocol: tcp }
          - { port: 2379, protocol: tcp }
          - { port: 2380, protocol: tcp }
          - { port: 10250, protocol: tcp }
          - { port: 10251, protocol: tcp }
          - { port: 10252, protocol: tcp }
          - { port: 10255, protocol: tcp }
          - { port: 30000-32767, protocol: tcp }

    - name: Add firewalld rules for Kubernetes ports
      firewalld:
        port: "{{ item.port }}/{{ item.protocol }}"
        state: enabled
        permanent: true
      loop: "{{ kubernetes_ports }}"
      notify: Reload firewalld

    - name: Enable IPv4 packet forwarding
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv4.ip_forward'
        line: 'net.ipv4.ip_forward = 1'
        state: present
      notify: Apply sysctl settings

  handlers:
    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded

    - name: Apply sysctl settings
      ansible.builtin.command: sysctl -p