# Autor: Francisco Javier Gutierrez | Unix/Linux Architect & Cloud Engineer
---
- name: Asegurarse de que nginx se encuentre instalado
  become: yes
  yum:
    name: nginx
    state: present

- name: Copiar archivo de configuracion principal de nginx
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Reiniciar nginx

- name: Copiar bloque de configuracion por defecto de nginx
  become: yes
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: Reiniciar nginx

- name: Asegurarse de que nginx se ha habilitado e iniciado
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes
