# Autor: Francisco Javiuer Gutierrez | Unix/Linux Architect & Cloud Engineer
- hosts: all
  become: yes
  roles:
    - common

- hosts: masters
  become: yes
  roles:
    - role: haproxy
    - role: keepalived
      vars:
        keepalived_state: "BACKUP"
        keepalived_priority: 100

- hosts: master1
  become: yes
  roles:
    - role: keepalived
      vars:
        keepalived_state: "MASTER"
        keepalived_priority: 101

- hosts: masters
  become: yes
  roles:
    - role: kubernetes

- hosts: workers
  become: yes
  roles:
    - role: kubernetes